sudo: false
cache:
  directories:
  - $HOME/.stack
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
script:
  - stack --no-terminal --skip-ghc-check test
git:
  submodules: false